### ISSUE TITLE
Your punt booker seems to be broken

### ISSUE THREAD

**Issue by epijim** [JCMCR/JesusMCRsite#2]
Hey, I'm an old website admin - and appear to still be connected to the punt form booker.

I'm getting lots of errors on the google script:

![screen shot 2018-03-20 at 09 14 10](https://user-images.githubusercontent.com/2760096/37642892-1b8fb394-2c1f-11e8-91fc-220587e8aeba.jpg)

**Comment by kritts** [comment]
The punt booker isn't broken, I've just removed the access of past admin. Are you still receiving emails about it?

**Comment by JJMinton** [comment]
I haven't in a few weeks.

**Comment by epijim** [comment]
Hi,

Haven't recieved emails since I think a day or two after I made the issue 16 days ago. Before then I was getting them every few days for maybe a week.

I guess my API key was cut before the script was updated to use new credentials or there was some other mismatch which is now resolved.

BW,

J
